name: Build and Test (SBT)

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Run tests
      run: |
        chmod +x ./mill
        ./mill shared.jvm.test
        
