name: Deploy JAR

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        run: |
          chmod +x ./mill
          ./mill jvm.assembly

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/jvm/assembly.test/FormulaFX.jar
          tag: ${{ github.ref }}
          overwrite: true
