name: Deploy JAR

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --add github.actor OndrejSpanel
          git config --add github.token ${{ secrets.GITHUB_TOKEN }}
          sbt projsJS/fullOptJS
          mkdir public
          cp js/target/scala-2.13/formulafx-opt.js public/.
          cp js/target/scala-2.13/index.html public/.

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: jvm/target/scala-2.13/FormulaFx.jar
          tag: ${{ github.ref }}
          overwrite: true
