name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        run: |
          chmod +x ./mill
          ./mill js.bundleOpt\
          mkdir public
          cp out/js/fullLinkJS.dest/main.js public/.
          cp out/js/generateIndexOpt.dest/index.html public/.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
